// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Paket.Bootstrapper")]
[assembly: AssemblyProductAttribute("Paket")]
[assembly: AssemblyDescriptionAttribute("A package dependency manager for .NET with support for NuGet packages and GitHub repositories.")]
[assembly: AssemblyVersionAttribute("2.58.11")]
[assembly: AssemblyFileVersionAttribute("2.58.11")]
[assembly: AssemblyInformationalVersionAttribute("2.58.11")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.58.11";
        internal const string InformationalVersion = "2.58.11";
    }
}
