// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Paket.Bootstrapper")]
[assembly: AssemblyProductAttribute("Paket")]
[assembly: AssemblyDescriptionAttribute("A dependency manager for .NET with support for NuGet packages and git repositories.")]
[assembly: AssemblyVersionAttribute("5.128.7")]
[assembly: AssemblyFileVersionAttribute("5.128.7")]
[assembly: AssemblyInformationalVersionAttribute("5.128.7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Paket.Bootstrapper";
        internal const System.String AssemblyProduct = "Paket";
        internal const System.String AssemblyDescription = "A dependency manager for .NET with support for NuGet packages and git repositories.";
        internal const System.String AssemblyVersion = "5.128.7";
        internal const System.String AssemblyFileVersion = "5.128.7";
        internal const System.String AssemblyInformationalVersion = "5.128.7";
    }
}
