// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Paket.Bootstrapper")]
[assembly: AssemblyProductAttribute("Paket")]
[assembly: AssemblyDescriptionAttribute("A dependency manager for .NET with support for NuGet packages and git repositories.")]
[assembly: AssemblyVersionAttribute("2.64.0")]
[assembly: AssemblyFileVersionAttribute("2.64.0")]
[assembly: AssemblyInformationalVersionAttribute("2.64.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.64.0";
        internal const string InformationalVersion = "2.64.0";
    }
}
