// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("PRI.LongPath")]
[assembly: AssemblyProductAttribute("Paket")]
[assembly: AssemblyDescriptionAttribute("A dependency manager for .NET with support for NuGet packages and git repositories.")]
[assembly: AssemblyVersionAttribute("5.84.0")]
[assembly: AssemblyFileVersionAttribute("5.84.0")]
[assembly: AssemblyInformationalVersionAttribute("5.84.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "PRI.LongPath";
        internal const System.String AssemblyProduct = "Paket";
        internal const System.String AssemblyDescription = "A dependency manager for .NET with support for NuGet packages and git repositories.";
        internal const System.String AssemblyVersion = "5.84.0";
        internal const System.String AssemblyFileVersion = "5.84.0";
        internal const System.String AssemblyInformationalVersion = "5.84.0";
    }
}
