case RbConfig::CONFIG['target_os']
when /windows|bccwin|cygwin|djgpp|mingw|mswin|wince/i
  notification :gntp, :host => 'localhost'
when /linux/i
  notification :notifysend
when /mac|darwin/i
  notification :growl
end

guard 'bundler' do
  watch('Gemfile')
end

guard :depend,
  # The path to the output generated by cmd. This can be a single value, an array or a callable returning any of both.
  output_paths: Proc.new { Dir['docs/output/**/*'] },

  # The command to run if the output is outdated or does not exist.
  cmd: %w(build.cmd GenerateDocs),

  # Whether to run at startup.
  run_on_start: true do
    watch(%r{^docs/(content|files)/})
end
