// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("PaketRestoreTask")]
[assembly: AssemblyProductAttribute("Paket")]
[assembly: AssemblyDescriptionAttribute("A dependency manager for .NET with support for NuGet packages and git repositories.")]
[assembly: AssemblyVersionAttribute("4.0.0")]
[assembly: AssemblyFileVersionAttribute("4.0.0")]
[assembly: AssemblyInformationalVersionAttribute("4.0.0-alpha001")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "4.0.0";
        internal const string InformationalVersion = "4.0.0-alpha001";
    }
}
