// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Paket.Core")>]
[<assembly: AssemblyProductAttribute("Paket")>]
[<assembly: AssemblyCompanyAttribute("Paket team")>]
[<assembly: AssemblyDescriptionAttribute("A dependency manager for .NET with support for NuGet packages and git repositories.")>]
[<assembly: AssemblyVersionAttribute("4.4.1")>]
[<assembly: AssemblyFileVersionAttribute("4.4.1")>]
[<assembly: AssemblyInformationalVersionAttribute("4.4.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Paket.Core"
    let [<Literal>] AssemblyProduct = "Paket"
    let [<Literal>] AssemblyCompany = "Paket team"
    let [<Literal>] AssemblyDescription = "A dependency manager for .NET with support for NuGet packages and git repositories."
    let [<Literal>] AssemblyVersion = "4.4.1"
    let [<Literal>] AssemblyFileVersion = "4.4.1"
    let [<Literal>] AssemblyInformationalVersion = "4.4.1"
