// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Paket")>]
[<assembly: AssemblyProductAttribute("Paket")>]
[<assembly: AssemblyCompanyAttribute("Paket team")>]
[<assembly: AssemblyDescriptionAttribute("A dependency manager for .NET with support for NuGet packages and git repositories.")>]
[<assembly: AssemblyVersionAttribute("5.92.100")>]
[<assembly: AssemblyFileVersionAttribute("5.92.100")>]
[<assembly: AssemblyInformationalVersionAttribute("5.92.100")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Paket"
    let [<Literal>] AssemblyProduct = "Paket"
    let [<Literal>] AssemblyCompany = "Paket team"
    let [<Literal>] AssemblyDescription = "A dependency manager for .NET with support for NuGet packages and git repositories."
    let [<Literal>] AssemblyVersion = "5.92.100"
    let [<Literal>] AssemblyFileVersion = "5.92.100"
    let [<Literal>] AssemblyInformationalVersion = "5.92.100"
