// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Paket.PowerShell")>]
[<assembly: AssemblyProductAttribute("Paket")>]
[<assembly: AssemblyCompanyAttribute("Paket team")>]
[<assembly: AssemblyDescriptionAttribute("A dependency manager for .NET with support for NuGet packages and git repositories.")>]
[<assembly: AssemblyVersionAttribute("3.27.01")>]
[<assembly: AssemblyFileVersionAttribute("3.27.01")>]
[<assembly: AssemblyInformationalVersionAttribute("3.27.01")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Paket.PowerShell"
    let [<Literal>] AssemblyProduct = "Paket"
    let [<Literal>] AssemblyCompany = "Paket team"
    let [<Literal>] AssemblyDescription = "A dependency manager for .NET with support for NuGet packages and git repositories."
    let [<Literal>] AssemblyVersion = "3.27.01"
    let [<Literal>] AssemblyFileVersion = "3.27.01"
    let [<Literal>] AssemblyInformationalVersion = "3.27.01"
